LO OBLIGATORIO
not find this vars in jobsite or jobdesc:(reqid,empname is default, title, location,source_salary, source_location, source_jobtype, source_benefit,expserience_required, daposted_raw, dateclosed_raw)
has expired jobs , 
has duplicated jobs
clean jobdesc as much as possible
No location was found (HQ has been setted).
the waits set are necessary to extract the complete information and not stuck





change waits in config for wait for selector, reduce run time AVG
clean date ago because generate insert problems replace with absolute date in span-json structured data in jobdesc
clean date ago because generate insert problems not found absolute date in script json
fixed locations as much as possible
add dateposted raw with structured data JSON script
Migrated to talent
Changed status in Talent and Neuvo.
reduce selector (clean css information or graphic)in extract




validar si existe la palabra multilocation, en un array poner las formas en diferentes idiomas
hacer un array como el de las limpiezas que me valide las vars en li , p, y se puedan agregar o quitar 
arreglar las descripciones para que vengan ya con las limpiezas de link y todo lo otro


//***************************************** */
COMPLETA:
reqid,empname, location (use HQ), source_location,source_salary source_jobtype, source_benefit,expserience_required, daposted_raw, dateclosed_raw


