        


        // MAPEO US

        // US STATES - TWO CODE LETTERS TO: "state"
        // Para modifcar el estado de dos letras a su nombre completo. 


        if(job.location.indexOf("USA")>-1){

          job.location = job.location.replace("USA","US");

          if(job.location.indexOf("AL") > -1) { job.location =  job.location.replace("AL","Alabama"); };
          if(job.location.indexOf("AK") > -1) { job.location =  job.location.replace("AK","Alaska"); };
          if(job.location.indexOf("AZ") > -1) { job.location =  job.location.replace("AZ","Arizona"); };
          if(job.location.indexOf("AR") > -1) { job.location =  job.location.replace("AR","Arkansas"); };
          if(job.location.indexOf("CA") > -1) { job.location =  job.location.replace("CA","California"); };
          if(job.location.indexOf("CO") > -1) { job.location =  job.location.replace("CO","Colorado"); };
          if(job.location.indexOf("CT") > -1) { job.location =  job.location.replace("CT","Connecticut");};
          if(job.location.indexOf("DE") > -1) { job.location =  job.location.replace("DE","Delaware"); };
          if(job.location.indexOf("FL") > -1) { job.location =  job.location.replace("FL","Florida"); };
          if(job.location.indexOf("GA") > -1) { job.location =  job.location.replace("GA","Georgia"); };
          if(job.location.indexOf("HI") > -1) { job.location =  job.location.replace("HI","Hawaii"); };
          if(job.location.indexOf("ID") > -1) { job.location =  job.location.replace("ID","Idaho"); };
          if(job.location.indexOf("IL") > -1) { job.location =  job.location.replace("IL","llinois"); };
          if(job.location.indexOf("IN") > -1) { job.location =  job.location.replace("IN","Indiana"); };
          if(job.location.indexOf("IA") > -1) { job.location =  job.location.replace("IA","Iowa"); };
          if(job.location.indexOf("KS") > -1) { job.location =  job.location.replace("KS","Kansas"); };
          if(job.location.indexOf("KY") > -1) { job.location =  job.location.replace("KY","Kentucky"); };
          if(job.location.indexOf("LA") > -1) { job.location =  job.location.replace("LA","Louisiana"); };
          if(job.location.indexOf("ME") > -1) { job.location =  job.location.replace("ME","Maine"); };
          if(job.location.indexOf("MD") > -1) { job.location =  job.location.replace("MD","Maryland"); };
          if(job.location.indexOf("MA") > -1) { job.location =  job.location.replace("MA","Massachusetts"); };
          if(job.location.indexOf("MI") > -1) { job.location =  job.location.replace("MI","Míchigan");}; 
          if(job.location.indexOf("MN") > -1) { job.location =  job.location.replace("MN","Minnesota"); };
          if(job.location.indexOf("MS") > -1) { job.location =  job.location.replace("MS","Mississippi"); };
          if(job.location.indexOf("MO") > -1) { job.location =  job.location.replace("MO","Missouri"); };
          if(job.location.indexOf("MT") > -1) { job.location =  job.location.replace("MT","Montana"); };
          if(job.location.indexOf("NE") > -1) { job.location =  job.location.replace("NE","Nebraska"); };
          if(job.location.indexOf("NV") > -1) { job.location =  job.location.replace("NV","Nevada"); }
          if(job.location.indexOf("NH") > -1) { job.location =  job.location.replace("NH","New Hampshire"); };
          if(job.location.indexOf("NJ") > -1) { job.location =  job.location.replace("NJ","New Jersey"); };
          if(job.location.indexOf("NM") > -1) { job.location =  job.location.replace("NM","New Mexico"); };
          if(job.location.indexOf("NY") > -1) { job.location =  job.location.replace("NY","New York"); };
          if(job.location.indexOf("NC") > -1) { job.location =  job.location.replace("NC","North Carolina"); };
          if(job.location.indexOf("ND") > -1) { job.location =  job.location.replace("ND","North Dakota"); };
          if(job.location.indexOf("OH") > -1) { job.location =  job.location.replace("OH","Ohio");};
          if(job.location.indexOf("OK") > -1) { job.location =  job.location.replace("OK","Oklahoma");};
          if(job.location.indexOf("OR") > -1) { job.location =  job.location.replace("OR","Oregon"); };
          if(job.location.indexOf("PA") > -1) { job.location =  job.location.replace("PA","Pennsylvania"); };
          if(job.location.indexOf("RI") > -1) { job.location =  job.location.replace("RI","Rhode Island"); };
          if(job.location.indexOf("SC") > -1) { job.location =  job.location.replace("SC","South Carolina"); };
          if(job.location.indexOf("SD") > -1) { job.location =  job.location.replace("SD","South Dakota"); };
          if(job.location.indexOf("TN") > -1) { job.location =  job.location.replace("TN","Tennessee"); };
          if(job.location.indexOf("TX") > -1) { job.location =  job.location.replace("TX","Texas"); };
          if(job.location.indexOf("UT") > -1) { job.location =  job.location.replace("UT","Utah"); };
          if(job.location.indexOf("VT") > -1) { job.location =  job.location.replace("VT","Vermont"); };
          if(job.location.indexOf("VA") > -1) { job.location =  job.location.replace("VA","Virginia"); };
          if(job.location.indexOf("WA") > -1) { job.location =  job.location.replace("WA","Washington"); };
          if(job.location.indexOf("WV") > -1) { job.location =  job.location.replace("WV","West Virginia"); };
          if(job.location.indexOf("WI") > -1) { job.location =  job.location.replace("WI","Wisconsin"); };
          if(job.location.indexOf("WY") > -1) { job.location =  job.location.replace("WY","Wyoming"); }  ;

        }

    
         // US STATES + COUNTRY
         // Concatenar al estado el país 
         job.location =  job.location.replace("Alabama", "Alabama, US");
         job.location =  job.location.replace("Alaska", "Alaska, US"); 
         job.location =  job.location.replace("Arizona", "Arizona, US"); 
         job.location =  job.location.replace("Arkansas", "Arkansas, US"); 
         job.location =  job.location.replace("California", "California, US"); 
         job.location =  job.location.replace("Colorado", "Colorado, US"); 
         job.location =  job.location.replace("Connecticut", "Connecticut, US");
         job.location =  job.location.replace("Delaware", "Delaware, US"); 
         job.location =  job.location.replace("Florida", "Florida, US"); 
         job.location =  job.location.replace("Georgia", "Georgia, US");
         job.location =  job.location.replace("Hawaii", "Hawaii, US"); 
         job.location =  job.location.replace("Idaho", "Idaho, US"); 
         job.location =  job.location.replace("llinois", "llinois, US"); 
         job.location =  job.location.replace("Indiana", "Indiana, US"); 
         job.location =  job.location.replace("Iowa", "Iowa, US"); 
         job.location =  job.location.replace("Kansas", "Kansas, US"); 
         job.location =  job.location.replace("Kentucky", "Kentucky, US"); 
         job.location =  job.location.replace("Louisiana", "Louisiana, US"); 
         job.location =  job.location.replace("Maine", "Maine, US"); 
         job.location =  job.location.replace("Maryland", "Maryland, US"); 
         job.location =  job.location.replace("Massachusetts", "Massachusetts, US"); 
         job.location =  job.location.replace("Michigan", "Michigan, US"); 
         job.location =  job.location.replace("Minnesota", "Minnesota, US"); 
         job.location =  job.location.replace("Mississippi", "Mississippi, US"); 
         job.location =  job.location.replace("Missouri", "Missouri, US"); 
         job.location =  job.location.replace("Montana", "Montana, US");
         job.location =  job.location.replace("Nebraska", "Nebraska, US"); 
         job.location =  job.location.replace("Nevada", "Nevada, US");
         job.location =  job.location.replace("New Hampshire", "New Hampshire, US"); 
         job.location =  job.location.replace("New Jersey", "New Jersey, US"); 
         job.location =  job.location.replace("New Mexico", "New Mexico, US"); 
         job.location =  job.location.replace("New York", "New York, US"); 
         job.location =  job.location.replace("North Carolina", "North Carolina, US"); 
         job.location =  job.location.replace("North Dakota", "North Dakota, US"); 
         job.location =  job.location.replace("Ohio", "Ohio, US");
         job.location =  job.location.replace("Oklahoma", "Oklahoma, US");
         job.location =  job.location.replace("Oregon", "Oregon, US"); 
         job.location =  job.location.replace("Pennsylvania", "Pennsylvania, US"); 
         job.location =  job.location.replace("Rhode Island", "Rhode Island, US"); 
         job.location =  job.location.replace("South Carolina", "South Carolina, US");
         job.location =  job.location.replace("South Dakota", "South Dakota, US"); 
         job.location =  job.location.replace("Tennessee", "Tennessee, US"); 
         job.location =  job.location.replace("Texas", "Texas, US"); 
         job.location =  job.location.replace("Utah", "Utah, US"); 
         job.location =  job.location.replace("Vermont", "Vermont, US"); 
         job.location =  job.location.replace("Virginia", "Virginia, US"); 
         job.location =  job.location.replace("West Virginia", "West Virginia, US"); 
         job.location =  job.location.replace("Wisconsin", "Wisconsin, US"); 
         job.location =  job.location.replace("Wyoming", "Wyoming, US"); 


          // US STATES + COUNTRY
         // Concatenar al estado el país 

function concatenateUStoStates(loc){
         
         loc =  loc.replace("Alabama", "Alabama, US");
         loc =  loc.replace("Alaska", "Alaska, US"); 
         loc =  loc.replace("Arizona", "Arizona, US"); 
         loc =  loc.replace("Arkansas", "Arkansas, US"); 
         loc =  loc.replace("California", "California, US"); 
         loc =  loc.replace("Colorado", "Colorado, US"); 
         loc =  loc.replace("Connecticut", "Connecticut, US");
         loc =  loc.replace("Delaware", "Delaware, US"); 
         loc =  loc.replace("Florida", "Florida, US"); 
         loc =  loc.replace("Georgia", "Georgia, US");
         loc =  loc.replace("Hawaii", "Hawaii, US"); 
         loc =  loc.replace("Idaho", "Idaho, US"); 
         loc =  loc.replace("llinois", "llinois, US"); 
         loc =  loc.replace("Indiana", "Indiana, US"); 
         loc =  loc.replace("Iowa", "Iowa, US"); 
         loc =  loc.replace("Kansas", "Kansas, US"); 
         loc =  loc.replace("Kentucky", "Kentucky, US"); 
         loc =  loc.replace("Louisiana", "Louisiana, US"); 
         loc =  loc.replace("Maine", "Maine, US"); 
         loc =  loc.replace("Maryland", "Maryland, US"); 
         loc =  loc.replace("Massachusetts", "Massachusetts, US"); 
         loc =  loc.replace("Michigan", "Michigan, US"); 
         loc =  loc.replace("Minnesota", "Minnesota, US"); 
         loc =  loc.replace("Mississippi", "Mississippi, US"); 
         loc =  loc.replace("Missouri", "Missouri, US"); 
         loc =  loc.replace("Montana", "Montana, US");
         loc =  loc.replace("Nebraska", "Nebraska, US"); 
         loc =  loc.replace("Nevada", "Nevada, US");
         loc =  loc.replace("New Hampshire", "New Hampshire, US"); 
         loc =  loc.replace("New Jersey", "New Jersey, US"); 
         loc =  loc.replace("New Mexico", "New Mexico, US"); 
         loc =  loc.replace("New York", "New York, US"); 
         loc =  loc.replace("North Carolina", "North Carolina, US"); 
         loc =  loc.replace("North Dakota", "North Dakota, US"); 
         loc =  loc.replace("Ohio", "Ohio, US");
         loc =  loc.replace("Oklahoma", "Oklahoma, US");
         loc =  loc.replace("Oregon", "Oregon, US"); 
         loc =  loc.replace("Pennsylvania", "Pennsylvania, US"); 
         loc =  loc.replace("Rhode Island", "Rhode Island, US"); 
         loc =  loc.replace("South Carolina", "South Carolina, US");
         loc =  loc.replace("South Dakota", "South Dakota, US"); 
         loc =  loc.replace("Tennessee", "Tennessee, US"); 
         loc =  loc.replace("Texas", "Texas, US"); 
         loc =  loc.replace("Utah", "Utah, US"); 
         loc =  loc.replace("Vermont", "Vermont, US"); 
         loc =  loc.replace("Virginia", "Virginia, US"); 
         loc =  loc.replace("West Virginia", "West Virginia, US"); 
         loc =  loc.replace("Wisconsin", "Wisconsin, US"); 
         loc =  loc.replace("Wyoming", "Wyoming, US"); 

         return loc;

     }
       

       // Cities of California

        //  Ayuda a que el GEO no les haga Mapping como Canada

       if(job.location.indexOf("Los Angeles")>-1){job.location = "Los Angeles, CA, US";}
       if(job.location.indexOf("San Francisco")>-1){job.location = "San Francisco, CA, US";}
       if(job.location.indexOf("San Diego")>-1){job.location = "San Diego, CA, US";}
       if(job.location.indexOf("Sacramento")>-1){job.location = "Sacramento, CA, US";}
       if(job.location.indexOf("San Jose")>-1){job.location = "San Jose, CA, US";}
       if(job.location.indexOf("Fresno")>-1){job.location = "Fresno, CA, US";}
       if(job.location.indexOf("Oakland")>-1){job.location = "Oakland, CA, US";}
       if(job.location.indexOf("Long Beach")>-1){job.location = "Long Beach, CA, US";}
       if(job.location.indexOf("Bakersfield")>-1){job.location = "Bakersfield, CA, US";}
       if(job.location.indexOf("Riverside")>-1){job.location = "Riverside, CA, US";}
       if(job.location.indexOf("Anaheim")>-1){job.location = "Anaheim, CA, US";}
       if(job.location.indexOf("Irvine")>-1){job.location = "Irvine, CA, US";}
       if(job.location.indexOf("Santa Barbara")>-1){job.location = "Santa Barbara, CA, US";}
       if(job.location.indexOf("Stockton")>-1){job.location = "Stockton, CA, US";}
       if(job.location.indexOf("Pasadena")>-1){job.location = "Pasadena, CA, US";}
       if(job.location.indexOf("Santa Monica")>-1){job.location = "Santa Monica, CA, US";}
       if(job.location.indexOf("Palm Springs")>-1){job.location = "Palm Springs, CA, US";}
       if(job.location.indexOf("Monterrey")>-1){job.location = "Monterrey, CA, US";}
       if(job.location.indexOf("Modesto")>-1){job.location = "Modesto, CA, US";}
       if(job.location.indexOf("San Bernardino")>-1){job.location = "San Bernardino, CA, US";}
       if(job.location.indexOf("Beverly Hills")>-1){job.location = "Beverly Hills, CA, US";}
       if(job.location.indexOf("Santa Rosa")>-1){job.location = "Santa Rosa, CA, US";}
       if(job.location.indexOf("Santa Ana")>-1){job.location = "Santa Ana, CA, US";}
       if(job.location.indexOf("Santa Cruz")>-1){job.location = "Santa Cruz, CA, US";}
       if(job.location.indexOf("Freemont")>-1){job.location = "Freemont, CA, US";}
       if(job.location.indexOf("Oxnard")>-1){job.location = "Oxnard, CA, US";}
       if(job.location.indexOf("Pomona")>-1){job.location = "Pomona, CA, US";}
       if(job.location.indexOf("Huntintong Beach")>-1){job.location = "Huntintong Beach, CA, US";}
       if(job.location.indexOf("Malibu")>-1){job.location = "Malibu, CA, US";}
       if(job.location.indexOf("Ventura")>-1){job.location = "Ventura, CA, US";}
       if(job.location.indexOf("Burbank")>-1){job.location = "Burbank, CA, US";}
       if(job.location.indexOf("California City")>-1){job.location = "California City, CA, US";}
       if(job.location.indexOf("Santa Clara")>-1){job.location = "Santa Clara, CA, US";}
       if(job.location.indexOf("Newport Beach")>-1){job.location = "Newport Beach, CA, US";}
       if(job.location.indexOf("Carlsbad")>-1){job.location = "Carlsbad, CA, US";}
       if(job.location.indexOf("Oceanside")>-1){job.location = "Oceanside, CA, US";}
       if(job.location.indexOf("Temecula")>-1){job.location = "Temecula, CA, US";}
       if(job.location.indexOf("San Luis")>-1){job.location = "San Luis, CA, US";}
       if(job.location.indexOf("Sunny Vale")>-1){job.location = "Sunny Vale, CA, US";}
       if(job.location.indexOf("Compton")>-1){job.location = "Compton, CA, US";}
       if(job.location.indexOf("Carmel-by-the-Sea")>-1){job.location = "Carmel-by-the-Sea, CA, US";}
       if(job.location.indexOf("San Mateo")>-1){job.location = "San Mateo, CA, US";}
       if(job.location.indexOf("Laguna Beach")>-1){job.location = "Laguna Beach, CA, US";}
       if(job.location.indexOf("Calabasas")>-1){job.location = "Calabasas, CA, US";}
       if(job.location.indexOf("Cupertino")>-1){job.location = "Cupertino, CA, US";}
       if(job.location.indexOf("Menlo Park")>-1){job.location = "Menlo Park, CA, US";}
       if(job.location.indexOf("Pismo Beach")>-1){job.location = "Pismo Beach, CA, US";}
       if(job.location.indexOf("Solvang")>-1){job.location = "Solvang, CA, US";}
       if(job.location.indexOf("Ridgecrest")>-1){job.location = "Ridgecrest, CA, US";}
       if(job.location.indexOf("La Verne")>-1){job.location = "La Verne, CA, US";}
       if(job.location.indexOf("Mountain View")>-1){job.location = "Mountain View, CA, US";}
       if(job.location.indexOf("Foster City")>-1){job.location = "Foster City, CA, US";}
     

        // Para locaciones complicadas de USA que solo tengan el código de dos letras por estado

        if(job.location.indexOf("AL") > 1) { job.location =  job.location.replace("AL",", Alabama, US"); };
        if(job.location.indexOf("AK") > 1) { job.location =  job.location.replace("AK",", Alaska, US"); };
        if(job.location.indexOf("AZ") > 1) { job.location =  job.location.replace("AZ",", Arizona, US"); };
        if(job.location.indexOf("AR") > 1) { job.location =  job.location.replace("AR",", Arkansas, US"); };
        if(job.location.indexOf("CA") > 1) { job.location =  job.location.replace("CA",", California, US"); };
        if(job.location.indexOf("CO") > 1) { job.location =  job.location.replace("CO",", Colorado, US"); };
        if(job.location.indexOf("CT") > 1) { job.location =  job.location.replace("CT",", Connecticut, US");};
        if(job.location.indexOf("DE") > 1) { job.location =  job.location.replace("DE",", Delaware, US"); };
        if(job.location.indexOf("FL") > 1) { job.location =  job.location.replace("FL",", Florida, US"); };
        if(job.location.indexOf("GA") > 1) { job.location =  job.location.replace("GA",", Georgia, US"); };
        if(job.location.indexOf("HI") > 1) { job.location =  job.location.replace("HI",", Hawai, US"); };
        if(job.location.indexOf("ID") > 1) { job.location =  job.location.replace("ID",", Idaho, US"); };
        if(job.location.indexOf("IL") > 1) { job.location =  job.location.replace("IL",", llinois, US"); };
        if(job.location.indexOf("IN") > 1) { job.location =  job.location.replace("IN",", Indiana, US"); };
        if(job.location.indexOf("IA") > 1) { job.location =  job.location.replace("IA",", Iowa, US"); };
        if(job.location.indexOf("KS") > 1) { job.location =  job.location.replace("KS",", Kansas, US"); };
        if(job.location.indexOf("KY") > 1) { job.location =  job.location.replace("KY",", Kentucky, US"); };
        if(job.location.indexOf("LA") > 1) { job.location =  job.location.replace("LA",", Louisiana, US"); };
        if(job.location.indexOf("ME") > 1) { job.location =  job.location.replace("ME",", Maine, US"); };
        if(job.location.indexOf("MD") > 1) { job.location =  job.location.replace("MD",", Maryland, US"); };
        if(job.location.indexOf("MA") > 1) { job.location =  job.location.replace("MA",", Massachusetts, US"); };
        if(job.location.indexOf("MI") > 1) { job.location =  job.location.replace("MI",", Míchigan, US");}; 
        if(job.location.indexOf("MN") > 1) { job.location =  job.location.replace("MN",", Minnesota"); };
        if(job.location.indexOf("MS") > 1) { job.location =  job.location.replace("MN",", Mississippi, US"); };
        if(job.location.indexOf("MO") > 1) { job.location =  job.location.replace("MO",", Missouri, US"); };
        if(job.location.indexOf("MT") > 1) { job.location =  job.location.replace("MT",", Montana, US"); };
        if(job.location.indexOf("NE") > 1) { job.location =  job.location.replace("NE",", Nebraska, US"); };
        if(job.location.indexOf("NV") > 1) { job.location =  job.location.replace("NV",", Nevada, US"); }
        if(job.location.indexOf("NH") > 1) { job.location =  job.location.replace("NH",", New Hampshire, US"); };
        if(job.location.indexOf("NJ") > 1) { job.location =  job.location.replace("NJ",", New Jersey, US"); };
        if(job.location.indexOf("NM") > 1) { job.location =  job.location.replace("NM",", New Mexico, US"); };
        if(job.location.indexOf("NY") > 1) { job.location =  job.location.replace("NY",", New York, US"); };
        if(job.location.indexOf("NC") > 1) { job.location =  job.location.replace("NC",", North Carolina, US"); };
        if(job.location.indexOf("ND") > 1) { job.location =  job.location.replace("ND",", North Dakota, US"); };
        if(job.location.indexOf("OH") > 1) { job.location =  job.location.replace("OH",", Ohio, US");};
        if(job.location.indexOf("OK") > 1) { job.location =  job.location.replace("OK",", Oklahoma, US");};
        if(job.location.indexOf("OR") > 1) { job.location =  job.location.replace("OR",", Oregon, US"); };
        if(job.location.indexOf("PA") > 1) { job.location =  job.location.replace("PA",", Pennsylvania, US"); };
        if(job.location.indexOf("RI") > 1) { job.location =  job.location.replace("RI",", Rhode Island, US"); };
        if(job.location.indexOf("SC") > 1) { job.location =  job.location.replace("SC",", South Carolina, US"); };
        if(job.location.indexOf("SD") > 1) { job.location =  job.location.replace("SD",", South Dakota, US"); };
        if(job.location.indexOf("TN") > 1) { job.location =  job.location.replace("TN",", Tennessee, US"); };
        if(job.location.indexOf("TX") > 1) { job.location =  job.location.replace("TX",", Texas, US"); };
        if(job.location.indexOf("UT") > 1) { job.location =  job.location.replace("UT",", Utah, US"); };
        if(job.location.indexOf("VT") > 1) { job.location =  job.location.replace("VT",", Vermont, US"); };
        if(job.location.indexOf("VA") > 1) { job.location =  job.location.replace("VA",", Virginia, US"); };
        if(job.location.indexOf("WA") > 1) { job.location =  job.location.replace("WA",", Washington, US");};
        if(job.location.indexOf("WV") > 1) { job.location =  job.location.replace("WV",", West Virginia, US"); };
        if(job.location.indexOf("WI") > 1) { job.location =  job.location.replace("WI",", Wisconsin, US"); };
        if(job.location.indexOf("WY") > 1) { job.location =  job.location.replace("WY",", Wyoming, US"); };




     // GB Super Validation
 
    if(job.location.search(/Brighton/i)>-1){job.location = "Brighton, England";}
    if(job.location.search(/Exeter/i)>-1){job.location = "Exeter, England";}
    if(job.location.search(/Glasgow/i)>-1){job.location = "Glasgow, Scotland";}
    if(job.location.search(/Baguley/i)>-1){job.location = "Baguley, England";}
    if(job.location.search(/Cheshunt/i)>-1){job.location = "Cheshunt, England";}
    if(job.location.search(/Harrow/i)>-1){job.location = "Harrow, England";}
    if(job.location.search(/Torquay/i)>-1){job.location = "Torquay, England";}
    if(job.location.search(/London/i)>-1){job.location = "London, GB";}
    if(job.location.search(/Bristol/i)>-1){job.location = "Bristol, GB";}
    if(job.location.search(/Manchester/i)>-1){job.location = "Manchester, GB";}
    if(job.location.search(/Birmingham/i)>-1){job.location = "Birmingham, GB";}
    if(job.location.search(/Belfast/i)>-1){job.location = "Belfast, GB";}
    if(job.location.search(/Liverpool/i)>-1){job.location = "Liverpool, GB";}
    if(job.location.search(/Wirral/i)>-1){job.location = "Wirral, GB";}
    if(job.location.search(/City Of London/i)>-1){job.location = "City Of London, GB";}
    if(job.location.search(/Leeds/i)>-1){job.location = "Leeds, GB";}
    if(job.location.search(/Swindon/i)>-1){job.location = "Swindon, GB";}
    if(job.location.search(/Reading/i)>-1){job.location = "Reading, GB";}
    if(job.location.search(/Cardiff/i)>-1){job.location = "Cardiff, GB";}
    if(job.location.search(/Nottingham/i)>-1){job.location = "Nottingham, GB";}
    if(job.location.search(/Cheltenham/i)>-1){job.location = "Cheltenham, GB";}
    if(job.location.search(/Southampton/i)>-1){job.location = "Southampton, GB";}
    if(job.location.search(/Glasgow/i)>-1){job.location = "Glasgow, GB";}
    if(job.location.search(/Gloucester/i)>-1){job.location = "Gloucester, GB";}
    if(job.location.search(/Coventry/i)>-1){job.location = "Coventry, GB";}
    if(job.location.search(/Edinburgh/i)>-1){job.location = "Edinburgh, GB";}
    if(job.location.search(/Canterbury/i)>-1){job.location = "Canterbury, GB";}
    if(job.location.search(/Nottingham/i)>-1){job.location = "Nottingham, GB";}
    if(job.location.search(/Cheltenham/i)>-1){job.location = "  Cheltenham, GB";}
    if(job.location.search(/Southampton/i)>-1){job.location = "Southampton, GB";}
    if(job.location.search(/Glasgow/i)>-1){job.location = "Glasgow, GB";}
    if(job.location.search(/Gloucester/i)>-1){job.location = "Gloucester, GB";}
    if(job.location.search(/Coventry/i)>-1){job.location = "Coventry, GB";}
    if(job.location.search(/Edinburgh/i)>-1){job.location = "Edinburgh, GB";}
    if(job.location.search(/Canterbury/i)>-1){job.location = "Canterbury, GB";}
    if(job.location.search(/Cambridge/i)>-1){job.location = "Cambridge, GB";}
    if(job.location.search(/Swansea/i)>-1){job.location = "Swansea, GB";}
    if(job.location.search(/Leiceste/i)>-1){job.location = "Leicester, GB";}
    if(job.location.search(/Oxford/i)>-1){job.location = "Oxford, GB";}
    if(job.location.search(/Bath/i)>-1){job.location = "Bath, GB";}
    if(job.location.search(/Sheffield/i)>-1){job.location = "Sheffield, GB";}
    if(job.location.search(/United Kingdom/i)>-1){job.location = "United Kingdom, GB";}
    if(job.location.search(/Nottinghamshire/i)>-1){job.location = "Nottinghamshire, GB";}
    if(job.location.search(/Wolverhampton/i)>-1){job.location = "Wolverhampton, GB";}
    if(job.location.search(/Preston/i)>-1){job.location = "Preston, GB";}
    if(job.location.search(/Portsmouth/i)>-1){job.location = "Portsmouth, GB";}
    if(job.location.search(/Warrington/i)>-1){job.location = "Warrington, GB";}
    if(job.location.search(/Derbyshire/i)>-1){job.location = "Derbyshire, GB";}
    if(job.location.search(/Maidstone/i)>-1){job.location = "Maidstone, GB";}
    if(job.location.search(/Brighton/i)>-1){job.location = "Brighton, GB";}
    if(job.location.search(/Wigan/i)>-1){job.location = "Wigan, GB";}
    if(job.location.search(/Milton Keynes/i)>-1){job.location = "Milton Keynes, GB";}
    if(job.location.search(/Wokingham/i)>-1){job.location = "Wokingham, GB";}
    if(job.location.search(/Surrey/i)>-1){job.location = "Surrey, GB";}
    if(job.location.search(/Exeter/i)>-1){job.location = "Exeter, GB";}
    if(job.location.search(/Kent/i)>-1){job.location = "Kent, GB";}
    if(job.location.search(/Leicestershire/i)>-1){job.location = "Leicestershire, GB";}
    if(job.location.search(/Bromley/i)>-1){job.location = "Bromley, GB";}
    if(job.location.search(/Stockport/i)>-1){job.location = "Stockport, GB";}
    if(job.location.search(/Stoke On Trent/i)>-1){job.location = "Stoke On Trent, GB";}
    if(job.location.search(/Bournemouth/i)>-1){job.location = "Bournemouth, GB";}
    if(job.location.search(/Northamptonshire/i)>-1){job.location = "Northamptonshire, GB";}
    if(job.location.search(/Slough/i)>-1){job.location = "Slough, GB";}
    if(job.location.search(/Chichester/i)>-1){job.location = "Chichester, GB";}
    if(job.location.search(/Hull/i)>-1){job.location = "Hull, GB";}
    if(job.location.search(/Doncaster/i)>-1){job.location = "Doncaster, GB";}
    if(job.location.search(/Hertfordshire/i)>-1){job.location = "Hertfordshire, GB";}
    if(job.location.search(/Crawley/i)>-1){job.location = "Crawley, GB";}
    if(job.location.search(/Newcastle (Tyne & Wear)/i)>-1){job.location = "Newcastle (Tyne & Wear), GB";}
    if(job.location.search(/Croydon/i)>-1){job.location = "Croydon, GB";}
    if(job.location.search(/Camden/i)>-1){job.location = "Camden, GB";}
    if(job.location.search(/Derby/i)>-1){job.location = "Derby, GB";}
    if(job.location.search(/Essex/i)>-1){job.location = "Essex, GB";}
    if(job.location.search(/Chester/i)>-1){job.location = "Chester, GB";}
    if(job.location.search(/Hampshire/i)>-1){job.location = "Hampshire, GB";}
    if(job.location.search(/Peterborough/i)>-1){job.location = "Peterborough, GB";}
    if(job.location.search(/Northampton/i)>-1){job.location = "Northampton, GB";}
    if(job.location.search(/Wakefield/i)>-1){job.location = "Wakefield, GB";}
    if(job.location.search(/Norwich/i)>-1){job.location = "Norwich, GB";}
    if(job.location.search(/Ipswich/i)>-1){job.location = "Ipswich, GB";}
    if(job.location.search(/Devizes/i)>-1){job.location = "Devizes, GB";}
    if(job.location.search(/Walsall/i)>-1){job.location = "Walsall, GB";}
    if(job.location.search(/Blackburn/i)>-1){job.location = "Blackburn, GB";}
    if(job.location.search(/Haywards Heath/i)>-1){job.location = "Haywards Heath, GB";}
    if(job.location.search(/Ealing/i)>-1){job.location = "Ealing, GB";}
    if(job.location.search(/Chippenham/i)>-1){job.location = "Chippenham, GB";}
    if(job.location.search(/South Gloucestershire/i)>-1){job.location = "South Gloucestershire, GB";}
    if(job.location.search(/Bradford/i)>-1){job.location = "Bradford, GB";}
    if(job.location.search(/Worthing/i)>-1){job.location = "Worthing, GB";}
    if(job.location.search(/Huddersfield/i)>-1){job.location = "Huddersfield, GB";}
    if(job.location.search(/Ashford/i)>-1){job.location = "Ashford, GB";}
    if(job.location.search(/Staffordshire /i)>-1){job.location = "Staffordshire, GB";}
    if(job.location.search(/Oxfordshire /i)>-1){job.location = "Oxfordshire, GB";}
    if(job.location.search(/Horsham/i)>-1){job.location = "Horsham, GB";}
    if(job.location.search(/Hatfield/i)>-1){job.location = "Hatfield, GB";}
    if(job.location.search(/Antrim/i)>-1){job.location = "Antrim, GB";}
    if(job.location.search(/Gloucestershire/i)>-1){job.location = "Gloucestershire, GB";}
    if(job.location.search(/Newport (South Wales)/i)>-1){job.location = "Newport (South Wales), GB";}
    if(job.location.search(/Bolton/i)>-1){job.location = "Bolton, GB";}
    if(job.location.search(/Guildford/i)>-1){job.location = "Guildford, GB";}
    if(job.location.search(/West Midlands/i)>-1){job.location = "West Midlands , GB";}
    if(job.location.search(/Luton/i)>-1){job.location = "Luton, GB";}
    if(job.location.search(/Colchester/i)>-1){job.location = "Colchester, GB";}
    if(job.location.search(/York/i)>-1){job.location = "York, GB";}
    if(job.location.search(/Nuneaton/i)>-1){job.location = "Nuneaton, GB";}
    if(job.location.search(/Basingstoke/i)>-1){job.location = "Basingstoke, GB";}
    if(job.location.search(/Warwick/i)>-1){job.location = "Warwick, GB";}
    if(job.location.search(/Leamington Spa/i)>-1){job.location = "Leamington Spa, GB";}
    if(job.location.search(/Warwickshire/i)>-1){job.location = "Warwickshire, GB";}
    if(job.location.search(/Cambridgeshire/i)>-1){job.location = "Cambridgeshire, GB";}
    if(job.location.search(/Cheshire/i)>-1){job.location = "Cheshire, GB";}
    if(job.location.search(/St Helens/i)>-1){job.location = "St Helens , GB";}
    if(job.location.search(/Glasgow & Strathclyde/i)>-1){job.location = "Glasgow & Strathclyde, GB";}
    if(job.location.search(/Salisbury/i)>-1){job.location = "Salisbury, GB";}
    if(job.location.search(/Southend-on-sea/i)>-1){job.location = "Southend-on-sea, GB";}
    if(job.location.search(/Plymouth/i)>-1){job.location = "Plymouth, GB";}
    if(job.location.search(/Northern Ireland/i)>-1){job.location = "Northern Ireland";}
    if(job.location.search(/Telford/i)>-1){job.location = "Telford, GB";}
    if(job.location.search(/Stratford Upon Avon/i)>-1){job.location = "Stratford Upon Avon, GB";}
    if(job.location.search(/Dover/i)>-1){job.location = "Dover, GB";}
    if(job.location.search(/Poole/i)>-1){job.location = "Poole, GB";}
    if(job.location.search(/Edinburgh & Lothian/i)>-1){job.location = "Edinburgh & Lothian, GB";}
    if(job.location.search(/Macclesfield/i)>-1){job.location = "Macclesfield, GB";}
    if(job.location.search(/Chelmsford/i)>-1){job.location = "Chelmsford, GB";}
    if(job.location.search(/Stroud/i)>-1){job.location = "Stroud  , GB";}
    if(job.location.search(/Rugby/i)>-1){job.location = "Rugby , GB";}
    if(job.location.search(/Solihull/i)>-1){job.location = "Solihull, GB";}
    if(job.location.search(/Hounslow/i)>-1){job.location = "Hounslow, GB";}
    if(job.location.search(/Kingston Upon Thames/i)>-1){job.location = "Kingston Upon Thames, GB";}
    if(job.location.search(/Lisburn/i)>-1){job.location = "Lisburn , GB";}
    if(job.location.search(/Caerphilly/i)>-1){job.location = "Caerphilly, GB";}
    if(job.location.search(/Norfolk/i)>-1){job.location = "Norfolk , GB";}
    if(job.location.search(/Chesterfield/i)>-1){job.location = "Chesterfield, GB";}
    if(job.location.search(/Oldham/i)>-1){job.location = "Oldham  , GB";}
    if(job.location.search(/Darlington/i)>-1){job.location = "Darlington, GB";}
    if(job.location.search(/Faringdon/i)>-1){job.location = "Faringdon, GB";}
    if(job.location.search(/Marlborough/i)>-1){job.location = "Marlborough, GB";}
    if(job.location.search(/Port Talbot/i)>-1){job.location = "Port Talbot, GB";}
    if(job.location.search(/Winchester/i)>-1){job.location = "Winchester, GB";}
    if(job.location.search(/Deal/i)>-1){job.location = "Deal, GB";}
    if(job.location.search(/Dungannon/i)>-1){job.location = "Dungannon, GB";}
    if(job.location.search(/Dudley/i)>-1){job.location = "Dudley, GB";}
    if(job.location.search(/North West/i)>-1){job.location = "North West, GB";}
    if(job.location.search(/Melksham/i)>-1){job.location = "Melksham, GB";}
    if(job.location.search(/Bridgend/i)>-1){job.location = "Bridgend, GB";}
    if(job.location.search(/Barnsley/i)>-1){job.location = "Barnsley, GB";}
    if(job.location.search(/Lancashire/i)>-1){job.location = "Lancashire, GB";}
    if(job.location.search(/Merseyside/i)>-1){job.location = "Merseyside, GB";}
    if(job.location.search(/Central London/i)>-1){job.location = "Central London, GB";}
    if(job.location.search(/High Wycombe/i)>-1){job.location = "High Wycombe, GB";}
    if(job.location.search(/Bury/i)>-1){job.location = "Bury, GB";}
    if(job.location.search(/Margate/i)>-1){job.location = "Margate, GB";}
    if(job.location.search(/Altrincham/i)>-1){job.location = "Altrincham, GB";}
    if(job.location.search(/Woking/i)>-1){job.location = "Woking, GB";}
    if(job.location.search(/Stoke-on-trent/i)>-1){job.location = "Stoke-on-trent, GB";}
    if(job.location.search(/Burnley/i)>-1){job.location = "Burnley, GB";}
    if(job.location.search(/Taunton/i)>-1){job.location = "Taunton, GB";}
    if(job.location.search(/County Tyrone/i)>-1){job.location = "County Tyrone, GB";}
    if(job.location.search(/Richmond Upon Thames/i)>-1){job.location = "Richmond Upon Thames, GB";}
    if(job.location.search(/Watford/i)>-1){job.location = "Watford, GB";}
    if(job.location.search(/Hereford/i)>-1){job.location = "Hereford, GB";}
    if(job.location.search(/Hackney/i)>-1){job.location = "Hackney, GB";}
    if(job.location.search(/Derry/i)>-1){job.location = "Derry, GB";}
    if(job.location.search(/Hammersmith And Fulham/i)>-1){job.location = "Hammersmith And Fulham, GB";}
    if(job.location.search(/Greater Manchester/i)>-1){job.location = "Greater Manchester, GB";}
    if(job.location.search(/Berkshire/i)>-1){job.location = "Berkshire, GB";}
    if(job.location.search(/Weybridge/i)>-1){job.location = "Weybridge, GB";}
    if(job.location.search(/Folkestone/i)>-1){job.location = "Folkestone, GB";}
    if(job.location.search(/Medway/i)>-1){job.location = "Medway, GB";}
    if(job.location.search(/Wilmslow/i)>-1){job.location = "Wilmslow, GB";}
    if(job.location.search(/Newbury/i)>-1){job.location = "Newbury, GB";}
    if(job.location.search(/Newham/i)>-1){job.location = "Newham, GB";}
    if(job.location.search(/Tameside/i)>-1){job.location = "Tameside, GB";}
    if(job.location.search(/Hastings/i)>-1){job.location = "Hastings, GB";}
    if(job.location.search(/Worcester/i)>-1){job.location = "Worcester, GB";}
    if(job.location.search(/South Yorkshire/i)>-1){job.location = "South Yorkshire, GB";}
    if(job.location.search(/North London/i)>-1){job.location = "London, GB";}
    if(job.location.search(/Lincoln/i)>-1){job.location = "Lincoln, GB";}
    if(job.location.search(/South London/i)>-1){job.location = "London, GB";}
    if(job.location.search(/Bracknell/i)>-1){job.location = "Bracknell, GB";}
    if(job.location.search(/Bury St Edmunds/i)>-1){job.location = "Bury St Edmunds , GB";}
    if(job.location.search(/Sefton/i)>-1){job.location = "Sefton, GB";}
    if(job.location.search(/Inverness/i)>-1){job.location = "Inverness, GB";}
    if(job.location.search(/Bedford/i)>-1){job.location = "Bedford, GB";}
    if(job.location.search(/Salford/i)>-1){job.location = "Salford, GB";}
    if(job.location.search(/County Down/i)>-1){job.location = "County Down, GB";}
    if(job.location.search(/Lincolnshire/i)>-1){job.location = "Lincolnshire, GB";}
    if(job.location.search(/Eastbourne/i)>-1){job.location = "Eastbourne, GB";}
    if(job.location.search(/Sittingbourne/i)>-1){job.location = "Sittingbourne, GB";}
    if(job.location.search(/Rotherham/i)>-1){job.location = "Rotherham, GB";}
    if(job.location.search(/Kings Lynn/i)>-1){job.location = "Kings Lynn, GB";}
    if(job.location.search(/West London/i)>-1){job.location = "West London, GB";}
    if(job.location.search(/Bridgwater/i)>-1){job.location = "Bridgwater, GB";}
    if(job.location.search(/Thanet/i)>-1){job.location = "Thanet, GB";}
    if(job.location.search(/Aberdeen/i)>-1){job.location = "Aberdeen, GB";}
    if(job.location.search(/Remote/i)>-1){job.location = "GB";}
    if(job.location.search(/Huntingdon/i)>-1){job.location = "Huntingdon, GB";}
    if(job.location.search(/Kettering/i)>-1){job.location = "Kettering, GB";}
    if(job.location.search(/Forest Of Dean/i)>-1){job.location = "Forest Of Dean, GB";}
    if(job.location.search(/Lewes/i)>-1){job.location = "Lewes, GB";}
    if(job.location.search(/Newry/i)>-1){job.location = "Newry, GB";}
    if(job.location.search(/Grimsby/i)>-1){job.location = "Grimsby, GB";}
    if(job.location.search(/Cirencester/i)>-1){job.location = "Cirencester, GB";}
    if(job.location.search(/Midlands/i)>-1){job.location = "Midlands, GB";}
    if(job.location.search(/Sandwell/i)>-1){job.location = "Sandwell, GB";}
    if(job.location.search(/Portadow/i)>-1){job.location = "Portadown, GB";}
    if(job.location.search(/Maidenhe/i)>-1){job.location = "Maidenhead, GB";}
    if(job.location.search(/Ellesmere Port/i)>-1){job.location = "Ellesmere Port, GB";}
    if(job.location.search(/Stevenag/i)>-1){job.location = "Stevenage, GB";}
    if(job.location.search(/Halifa/i)>-1){job.location = "Halifax, GB";}
    if(job.location.search(/Haringey/i)>-1){job.location = "Haringey , GB";}
    if(job.location.search(/Carmarthenshir/i)>-1){job.location = "Carmarthenshire, GB";}
    if(job.location.search(/Suffol/i)>-1){job.location = "Suffolk, GB";}
    if(job.location.search(/Wellingborough/i)>-1){job.location = "Wellingborough, GB";}
    if(job.location.search(/Hillingdon/i)>-1){job.location = "Hillingdon, GB";}




// Función mapeo Francia por departamento

       // Departments of france + country
       function franceDPTS(state){

        state = state.replace(/\(/g, ', ');
        state = state.replace(/ , /g,", ");
        state = state.replace(/\)/g, '');


       state = state.replace("971","Guadeloupe");
       state = state.replace("972","Martinique");
       state = state.replace("973","Guyane");
       state = state.replace("974","La Réunion");
       state = state.replace("01","Ain, FR");
       state = state.replace("02","Aisne, FR");
       state = state.replace("03","Allier, FR");
       state = state.replace("04","Alpes-de-Haute-Provence, FR");
       state = state.replace("05","Hautes-Alpes, FR");
       state = state.replace("06","Alpes-Maritimes, FR");
       state = state.replace("07","Ardèche, FR");
       state = state.replace("08","Ardennes, FR");
       state = state.replace("09","Ariège, FR");
       state = state.replace("10","Aube, FR");
       state = state.replace("11","Aude, FR");
       state = state.replace("12","Aveyron, FR");
       state = state.replace("13","Bouches-du-Rhône, FR");
       state = state.replace("14","Calvados, FR");
       state = state.replace("15","Cantal, FR");
       state = state.replace("16","Charente, FR"); 
       state = state.replace("17","Charente-Maritime, FR"); 
       state = state.replace("18","Cher, FR");
       state = state.replace("19","Corrèze, FR");
       state = state.replace("21","Côte-d’Or, FR"); 
       state = state.replace("22","Côtes-d’Armor, FR"); 
       state = state.replace("23","Creuse, FR");
       state = state.replace("24","Dordogne, FR");
       state = state.replace("25","Doubs, FR");
       state = state.replace("26","Drôme, FR"); 
       state = state.replace("27","Eure, FR"); 
       state = state.replace("28","Eure-et-Loir, FR"); 
       state = state.replace("29","Finistère, FR"); 
       state = state.replace("30","Gard, FR");
       state = state.replace("31","Haute-Garonne, FR");  
       state = state.replace("32","Gers, FR");
       state = state.replace("33","Gironde, FR");
       state = state.replace("34","Hérault, FR"); 
       state = state.replace("35","Ille-et-Vilaine, FR");
       state = state.replace("36","Indre, FR");
       state = state.replace("37","Indre-et-Loire, FR"); 
       state = state.replace("38","Isère, FR");
       state = state.replace("39","Jura, FR"); 
       state = state.replace("40","Landes, FR");
       state = state.replace("41","Loir-et-Cher, FR");
       state = state.replace("42","Loire, FR");
       state = state.replace("43","Haute-Loire, FR");
       state = state.replace("44","Loire-Atlantique, FR");
       state = state.replace("45","Loiret, FR");
       state = state.replace("46","Lot, FR");
       state = state.replace("47","Lot-et-Garonne, FR");
       state = state.replace("48","Lozère, FR");
       state = state.replace("49","Maine-et-Loire, FR");
       state = state.replace("50","Manche, FR");
       state = state.replace("51","Marne, FR");
       state = state.replace("52","Haute-Marne, FR");
       state = state.replace("53","Mayenne, FR");
       state = state.replace("54","Meurthe-et-Moselle, FR");
       state = state.replace("55","Meuse, FR");
       state = state.replace("56","Morbihan, FR");
       state = state.replace("57","Moselle, FR");
       state = state.replace("58","Nièvre, FR");
       state = state.replace("59","Nord, FR");
       state = state.replace("60","Oise, FR");
       state = state.replace("61","Orne, FR");
       state = state.replace("62","Pas-de-Calais, FR");
       state = state.replace("63","Puy-de-Dôme, FR");
       state = state.replace("64","Pyrénées-Atlantiques, FR");
       state = state.replace("65","Hautes-Pyrénées, FR");
       state = state.replace("66","Pyrénées-Orientales, FR");
       state = state.replace("67","Bas-Rhin, FR");
       state = state.replace("68","Haut-Rhin, FR");
       state = state.replace("69","Rhône, FR");
       state = state.replace("70","Haute-Saône, FR");
       state = state.replace("71","Saône-et-Loire, FR");
       state = state.replace("72","Sarthe, FR");
       state = state.replace("73","Savoie, FR");
       state = state.replace("74","Haute-Savoie, FR");
       state = state.replace("75","Paris, FR");
       state = state.replace("76","Seine-Maritime, FR");
       state = state.replace("77","Seine-et-Marne, FR");
       state = state.replace("78","Yvelines, FR");
       state = state.replace("79","Deux-Sèvres, FR");
       state = state.replace("80","Somme, FR");
       state = state.replace("81","Tarn, FR");
       state = state.replace("82","Tarn-et-Garonne, FR");
       state = state.replace("83","Var, FR");
       state = state.replace("84","Vaucluse, FR");
       state = state.replace("85","Vendée, FR");
       state = state.replace("86","Vienne, FR");
       state = state.replace("87","Haute-Vienne, FR");
       state = state.replace("88","Vosges, FR");
       state = state.replace("89","Yonne, FR");
       state = state.replace("90","Territoire de Belfort, FR");
       state = state.replace("91","Essonne, FR");
       state = state.replace("92","Hauts-de-Seine, FR");
       state = state.replace("93","Seine-Saint-Denis, FR");
       state = state.replace("94","Val-de-Marne, FR");
       state = state.replace("95","Val-d’Oise, FR");

return state;
}

// Función Código ISO 3 letras a País

function TLCtoCountry(loc){
    loc = loc.replace("AFG","Afghanistan");
    loc = loc.replace("ALA","Aland Islands");
    loc = loc.replace("ALB","Albania");
    loc = loc.replace("DZA","Algeria");
    loc = loc.replace("ASM","American Samoa");
    loc = loc.replace("AND","Andorra");
    loc = loc.replace("AGO","Angola");
    loc = loc.replace("AIA","Anguilla");
    loc = loc.replace("ATA","Antarctica");
    loc = loc.replace("ATG","Antigua and Barbuda");
    loc = loc.replace("ARG","Argentina");
    loc = loc.replace("ARM","Armenia");
    loc = loc.replace("ABW","Aruba");
    loc = loc.replace("AUS","Australia");
    loc = loc.replace("AUT","Austria");
    loc = loc.replace("AZE","Azerbaijan");
    loc = loc.replace("BHS","Bahamas");
    loc = loc.replace("BHR","Bahrain");
    loc = loc.replace("BGD","Bangladesh");
    loc = loc.replace("BRB","Barbados");
    loc = loc.replace("BLR","Belarus");
    loc = loc.replace("BEL","Belgium");
    loc = loc.replace("BLZ","Belize");
    loc = loc.replace("BEN","Benin");
    loc = loc.replace("BMU","Bermuda");
    loc = loc.replace("BTN","Bhutan");
    loc = loc.replace("BOL","Bolivia");
    loc = loc.replace("BES","Bonaire, Saint Eustatius and Saba");
    loc = loc.replace("BIH","Bosnia and Herzegovina");
    loc = loc.replace("BWA","Botswana");
    loc = loc.replace("BVT","Bouvet Island");
    loc = loc.replace("BRA","Brazil");
    loc = loc.replace("IOT","British Indian Ocean Territory");
    loc = loc.replace("VGB","British Virgin Islands");
    loc = loc.replace("BRN","Brunei");
    loc = loc.replace("BGR","Bulgaria");
    loc = loc.replace("BFA","Burkina Faso");
    loc = loc.replace("BDI","Burundi");
    loc = loc.replace("KHM","Cambodia");
    loc = loc.replace("CMR","Cameroon");
    loc = loc.replace("CAN","Canada");
    loc = loc.replace("CPV","Cape Verde");
    loc = loc.replace("CYM","Cayman Islands");
    loc = loc.replace("CAF","Central African Republic");
    loc = loc.replace("TCD","Chad");
    loc = loc.replace("CHL","Chile");
    loc = loc.replace("CHN","China");
    loc = loc.replace("CXR","Christmas Island");
    loc = loc.replace("CCK","Cocos Islands");
    loc = loc.replace("COL","Colombia");
    loc = loc.replace("COM","Comoros");
    loc = loc.replace("COK","Cook Islands");
    loc = loc.replace("CRI","Costa Rica");
    loc = loc.replace("HRV","Croatia");
    loc = loc.replace("CUB","Cuba");
    loc = loc.replace("CUW","Curacao");
    loc = loc.replace("CYP","Cyprus");
    loc = loc.replace("CZE","Czech Republic");
    loc = loc.replace("COD","Democratic Republic of the Congo");
    loc = loc.replace("DNK","Denmark");
    loc = loc.replace("DJI","Djibouti");
    loc = loc.replace("DMA","Dominica");
    loc = loc.replace("DOM","Dominican Republic");
    loc = loc.replace("TLS","East Timor");
    loc = loc.replace("ECU","Ecuador");
    loc = loc.replace("EGY","Egypt");
    loc = loc.replace("SLV","El Salvador");
    loc = loc.replace("GNQ","Equatorial Guinea");
    loc = loc.replace("ERI","Eritrea");
    loc = loc.replace("EST","Estonia");
    loc = loc.replace("ETH","Ethiopia");
    loc = loc.replace("FLK","Falkland Islands");
    loc = loc.replace("FRO","Faroe Islands");
    loc = loc.replace("FJI","Fiji");
    loc = loc.replace("FIN","Finland");
    loc = loc.replace("FRA","France");
    loc = loc.replace("GUF","French Guiana");
    loc = loc.replace("PYF","French Polynesia");
    loc = loc.replace("ATF","French Southern Territories");
    loc = loc.replace("GAB","Gabon");
    loc = loc.replace("GMB","Gambia");
    loc = loc.replace("GEO","Georgia");
    loc = loc.replace("DEU","Germany");
    loc = loc.replace("GHA","Ghana");
    loc = loc.replace("GIB","Gibraltar");
    loc = loc.replace("GRC","Greece");
    loc = loc.replace("GRL","Greenland");
    loc = loc.replace("GRD","Grenada");
    loc = loc.replace("GLP","Guadeloupe");
    loc = loc.replace("GUM","Guam");
    loc = loc.replace("GTM","Guatemala");
    loc = loc.replace("GGY","Guernsey");
    loc = loc.replace("GIN","Guinea");
    loc = loc.replace("GNB","Guinea-Bissau");
    loc = loc.replace("GUY","Guyana");
    loc = loc.replace("HTI","Haiti");
    loc = loc.replace("HMD","Heard Island and McDonald Islands");
    loc = loc.replace("HND","Honduras");
    loc = loc.replace("HKG","Hong Kong");
    loc = loc.replace("HUN","Hungary");
    loc = loc.replace("ISL","Iceland");
    loc = loc.replace("IND","India");
    loc = loc.replace("IDN","Indonesia");
    loc = loc.replace("IRN","Iran");
    loc = loc.replace("IRQ","Iraq");
    loc = loc.replace("IRL","Ireland");
    loc = loc.replace("IMN","Isle of Man");
    loc = loc.replace("ISR","Israel");
    loc = loc.replace("ITA","Italy");
    loc = loc.replace("CIV","Ivory Coast");
    loc = loc.replace("JAM","Jamaica");
    loc = loc.replace("JPN","Japan");
    loc = loc.replace("JEY","Jersey");
    loc = loc.replace("JOR","Jordan");
    loc = loc.replace("KAZ","Kazakhstan");
    loc = loc.replace("KEN","Kenya");
    loc = loc.replace("KIR","Kiribati");
    loc = loc.replace("XKX","Kosovo");
    loc = loc.replace("KWT","Kuwait");
    loc = loc.replace("KGZ","Kyrgyzstan");
    loc = loc.replace("LAO","Laos");
    loc = loc.replace("LVA","Latvia");
    loc = loc.replace("LBN","Lebanon");
    loc = loc.replace("LSO","Lesotho");
    loc = loc.replace("LBR","Liberia");
    loc = loc.replace("LBY","Libya");
    loc = loc.replace("LIE","Liechtenstein");
    loc = loc.replace("LTU","Lithuania");
    loc = loc.replace("LUX","Luxembourg");
    loc = loc.replace("MAC","Macao");
    loc = loc.replace("MKD","Macedonia");
    loc = loc.replace("MDG","Madagascar");
    loc = loc.replace("MWI","Malawi");
    loc = loc.replace("MYS","Malaysia");
    loc = loc.replace("MDV","Maldives");
    loc = loc.replace("MLI","Mali");
    loc = loc.replace("MLT","Malta");
    loc = loc.replace("MHL","Marshall Islands");
    loc = loc.replace("MTQ","Martinique");
    loc = loc.replace("MRT","Mauritania");
    loc = loc.replace("MUS","Mauritius");
    loc = loc.replace("MYT","Mayotte");
    loc = loc.replace("MEX","Mexico");
    loc = loc.replace("FSM","Micronesia");
    loc = loc.replace("MDA","Moldova");
    loc = loc.replace("MCO","Monaco");
    loc = loc.replace("MNG","Mongolia");
    loc = loc.replace("MNE","Montenegro");
    loc = loc.replace("MSR","Montserrat");
    loc = loc.replace("MAR","Morocco");
    loc = loc.replace("MOZ","Mozambique");
    loc = loc.replace("MMR","Myanmar");
    loc = loc.replace("NAM","Namibia");
    loc = loc.replace("NRU","Nauru");
    loc = loc.replace("NPL","Nepal");
    loc = loc.replace("NLD","Netherlands");
    loc = loc.replace("ANT","Netherlands Antilles");
    loc = loc.replace("NCL","New Caledonia");
    loc = loc.replace("NZL","New Zealand");
    loc = loc.replace("NIC","Nicaragua");
    loc = loc.replace("NER","Niger");
    loc = loc.replace("NGA","Nigeria");
    loc = loc.replace("NIU","Niue");
    loc = loc.replace("NFK","Norfolk Island");
    loc = loc.replace("PRK","North Korea");
    loc = loc.replace("MNP","Northern Mariana Islands");
    loc = loc.replace("NOR","Norway");
    loc = loc.replace("OMN","Oman");
    loc = loc.replace("PAK","Pakistan");
    loc = loc.replace("PLW","Palau");
    loc = loc.replace("PSE","Palestinian Territory");
    loc = loc.replace("PAN","Panama");
    loc = loc.replace("PNG","Papua New Guinea");
    loc = loc.replace("PRY","Paraguay");
    loc = loc.replace("PER","Peru");
    loc = loc.replace("PHL","Philippines");
    loc = loc.replace("PCN","Pitcairn");
    loc = loc.replace("POL","Poland");
    loc = loc.replace("PRT","Portugal");
    loc = loc.replace("PRI","Puerto Rico");
    loc = loc.replace("QAT","Qatar");
    loc = loc.replace("COG","Republic of the Congo");
    loc = loc.replace("REU","Reunion");
    loc = loc.replace("ROU","Romania");
    loc = loc.replace("RUS","Russia");
    loc = loc.replace("RWA","Rwanda");
    loc = loc.replace("BLM","Saint Barthelemy");
    loc = loc.replace("SHN","Saint Helena");
    loc = loc.replace("KNA","Saint Kitts and Nevis");
    loc = loc.replace("LCA","Saint Lucia");
    loc = loc.replace("MAF","Saint Martin");
    loc = loc.replace("SPM","Saint Pierre and Miquelon");
    loc = loc.replace("VCT","Saint Vincent and the Grenadines");
    loc = loc.replace("WSM","Samoa");
    loc = loc.replace("SMR","San Marino");
    loc = loc.replace("STP","Sao Tome and Principe");
    loc = loc.replace("SAU","Saudi Arabia ");
    loc = loc.replace("SEN","Senegal");
    loc = loc.replace("SRB","Serbia");
    loc = loc.replace("SCG","Serbia and Montenegro");
    loc = loc.replace("SYC","Seychelles");
    loc = loc.replace("SLE","Sierra Leone");
    loc = loc.replace("SGP","Singapore");
    loc = loc.replace("SXM","Sint Maarten");
    loc = loc.replace("SVK","Slovakia");
    loc = loc.replace("SVN","Slovenia");
    loc = loc.replace("SLB","Solomon Islands");
    loc = loc.replace("SOM","Somalia");
    loc = loc.replace("ZAF","South Africa");
    loc = loc.replace("SGS","South Georgia and the South Sandwich Islands");
    loc = loc.replace("KOR","South Korea");
    loc = loc.replace("SSD","South Sudan");
    loc = loc.replace("ESP","Spain");
    loc = loc.replace("LKA","Sri Lanka");
    loc = loc.replace("SDN","Sudan");
    loc = loc.replace("SUR","Suriname");
    loc = loc.replace("SJM","Svalbard and Jan Mayen");
    loc = loc.replace("SWZ","Swaziland");
    loc = loc.replace("SWE","Sweden");
    loc = loc.replace("CHE","Switzerland");
    loc = loc.replace("SYR","Syria");
    loc = loc.replace("TWN","Taiwan");
    loc = loc.replace("TJK","Tajikistan");
    loc = loc.replace("TZA","Tanzania");
    loc = loc.replace("THA","Thailand");
    loc = loc.replace("TGO","Togo");
    loc = loc.replace("TKL","Tokelau");
    loc = loc.replace("TON","Tonga");
    loc = loc.replace("TTO","Trinidad and Tobago");
    loc = loc.replace("TUN","Tunisia");
    loc = loc.replace("TUR","Turkey");
    loc = loc.replace("TKM","Turkmenistan");
    loc = loc.replace("TCA","Turks and Caicos Islands");
    loc = loc.replace("TUV","Tuvalu");
    loc = loc.replace("VIR","U.S. Virgin Islands");
    loc = loc.replace("UGA","Uganda");
    loc = loc.replace("UKR","Ukraine");
    loc = loc.replace("ARE","United Arab Emirates");
    loc = loc.replace("GBR","United Kingdom");
    loc = loc.replace("USA","United States");
    loc = loc.replace("UMI","United States Minor Outlying Islands");
    loc = loc.replace("URY","Uruguay");
    loc = loc.replace("UZB","Uzbekistan");
    loc = loc.replace("VUT","Vanuatu");
    loc = loc.replace("VAT","Vatican");
    loc = loc.replace("VEN","Venezuela");
    loc = loc.replace("VNM","Vietnam");
    loc = loc.replace("WLF","Wallis and Futuna");
    loc = loc.replace("ESH","Western Sahara");
    loc = loc.replace("YEM","Yemen");
    loc = loc.replace("ZMB","Zambia");
    loc = loc.replace("ZWE","Zimbabwe");

return loc;
}


// Alemania

/*Ciudades  y regiones de alemania*/
      if(job.location.indexOf("Augsburg")>-1){job.location = "Augsburg, DE";}
      if(job.location.indexOf("Bad Homburg")>-1){job.location = "Bad Homburg, DE";}
      if(job.location.indexOf("Bad Kreuznach")>-1){job.location = "Bad Kreuznach, DE";}
      if(job.location.indexOf("Bergisch Gladbach")>-1){job.location = "Bergisch Gladbach, DE";}
      if(job.location.indexOf("Köpenick")>-1){job.location = "Köpenick, Berlin, DE";}
      if(job.location.indexOf("Steglitz")>-1){job.location = "Steglitz, Berlin, DE";}
      if(job.location.indexOf("Spandau")>-1){job.location = "Spandau, Berlin, DE";}
      if(job.location.indexOf("Pankow")>-1){job.location = "Pankow, Berlin, DE";}
      if(job.location.indexOf("Braunschweig")>-1){job.location = "Braunschweig, DE";}
      if(job.location.indexOf("Dessau")>-1){job.location = "Dessau, DE";}
      if(job.location.indexOf("Dinslaken")>-1){job.location = "Dinslaken, DE";}
      if(job.location.indexOf("Dorsten")>-1){job.location = "Dorsten, DE";}
      if(job.location.indexOf("Dortmund")>-1){job.location = "Dortmund, DE";}
      if(job.location.indexOf("Dresden")>-1){job.location = "Dresden, DE";}
      if(job.location.indexOf("Detmold")>-1){job.location = "Detmold, DE";}
      if(job.location.indexOf("Düren")>-1){job.location = "Düren, DE";}
      if(job.location.indexOf("Frankfurt")>-1){job.location = "Frankfurt, DE";}
      if(job.location.indexOf("Dallgow-Döberitz")>-1){job.location = "Dallgow-Döberitz, DE";}
      if(job.location.indexOf("Coburg")>-1){job.location = "Coburg, DE";}
      if(job.location.indexOf("Celle")>-1){job.location = "Celle, DE";}
      if(job.location.indexOf("Bonn")>-1){job.location = "Bonn, DE";}
      if(job.location.indexOf("Bremen")>-1){job.location = "Bremen, DE";}
      if(job.location.indexOf("Bocholt")>-1){job.location = "Bocholt, DE";}
      if(job.location.indexOf("Berlin")>-1){job.location = "Berlin, DE";}
      if(job.location.indexOf("Mannheim")>-1){job.location = "Mannheim, DE";}
      if(job.location.indexOf("Mainz")>-1){job.location = "Mainz, DE";}
      if(job.location.indexOf("München")>-1){job.location = "München, DE";}
      if(job.location.indexOf("Wildau")>-1){job.location = "Wildau, DE";}
      if(job.location.indexOf("Wetzlar")>-1){job.location = "Wetzlar, DE";}
      if(job.location.indexOf("Stuttgart")>-1){job.location = "Stuttgart, DE";}
      if(job.location.indexOf("Unna")>-1){job.location = "Unna, DE";}
      if(job.location.indexOf("St. Pölten")>-1){job.location = "St. Pölten, Austria";}
      if(job.location.indexOf("Schweinfurt")>-1){job.location = "Schweinfurt, DE";}
      if(job.location.indexOf("Saarbrücken")>-1){job.location = "Saarbrücken, DE";}
      if(job.location.indexOf("Rostock")>-1){job.location = "Rostock, DE";}
      if(job.location.indexOf("Landau")>-1){job.location = "Landau, DE";}
      if(job.location.indexOf("Laatzen")>-1){job.location = "Laatzen, DE";}
      if(job.location.indexOf("Koblenz")>-1){job.location = "Koblenz, DE";}
      if(job.location.indexOf("Kiel")>-1){job.location = "Kiel, DE";}
      if(job.location.indexOf("Hildesheim")>-1){job.location = "Hildesheim, DE";}
      if(job.location.indexOf("Hannover")>-1){job.location = "Hannover, DE";}
      if(job.location.indexOf("Hanau")>-1){job.location = "Hanau, DE";}
      if(job.location.indexOf("Hamburg")>-1){job.location = "Hamburg, DE";}
      if(job.location.indexOf("Essen")>-1){job.location = "Essen, DE";}
      if(job.location.indexOf("Leipzig")>-1){job.location = "Leipzig, DE";}
      if(job.location.indexOf("Duisburg")>-1){job.location = "Duisburg, DE";}
      if(job.location.indexOf("Düsseldorf")>-1){job.location = "Düsseldorf, DE";}
      if(job.location.indexOf("Iserlohn")>-1){job.location = "Iserlohn, DE";}
      if(job.location.indexOf("Heilbronn")>-1){job.location = "Heilbronn, DE";}
      if(job.location.indexOf("Gera")>-1){job.location = "Gera, DE";}
      if(job.location.indexOf("Jena")>-1){job.location = "Jena, DE";}
      if(job.location.indexOf("Münster")>-1){job.location = "Münster, DE";}
      if(job.location.indexOf("Mönchengladbach")>-1){job.location = "Mönchengladbach, DE";}
      if(job.location.indexOf("Pforzheim")>-1){job.location = "Pforzheim, DE";}
      if(job.location.indexOf("Siegen")>-1){job.location = "Siegen, DE";}
      if(job.location.indexOf("Köln")>-1){job.location = "Köln, DE";}
      if(job.location.indexOf("Ingolstadt")>-1){job.location = "Ingolstadt, DE";}
      if(job.location.indexOf("Rosenheim")>-1){job.location = "Rosenheim, DE";}
      if(job.location.indexOf("Aachen")>-1){job.location = "Aachen, DE";}
      if(job.location.indexOf("Krefeld")>-1){job.location = "Krefeld, DE";}
      if(job.location.indexOf("Flensburg")>-1){job.location = "Flensburg, DE";}
      if(job.location.indexOf("Herford")>-1){job.location = "Herford, DE";}
      if(job.location.indexOf("Zwickau")>-1){job.location = "Zwickau, DE";}
      if(job.location.indexOf("Halle")>-1){job.location = "Halle, DE";}
      if(job.location.indexOf("Krefeld")>-1){job.location = "Krefeld, DE";}
      if(job.location.indexOf("Neuss")>-1){job.location = "Neuss, DE";}
      if(job.location.indexOf("Brandenburg ")>-1){job.location = "Brandenburg , DE";}
      if(job.location.indexOf("Moers")>-1){job.location = "Moers, DE";}
      if(job.location.indexOf("Bernburg")>-1){job.location = "Bernburg, DE";}
      if(job.location.indexOf("Ulm")>-1){job.location = "Ulm, DE";}
      if(job.location.indexOf("Stade")>-1){job.location = "Stade, DE";}
      if(job.location.indexOf("Rastatt")>-1){job.location = "Rastatt, DE";} 
      if(job.location.indexOf("Oberursel")>-1){job.location = "Oberursel, DE";}
      if(job.location.indexOf("Bruchsal")>-1){job.location = "Bruchsal, DE";}
      if(job.location.indexOf("Dormagen")>-1){job.location = "Dormagen, DE";}
      if(job.location.indexOf("Fürstenfeldbruck")>-1){job.location = "Fürstenfeldbruck, DE";}
      if(job.location.indexOf("Kassel")>-1){job.location = "Kassel, DE";}  
      if(job.location.indexOf("Gotha")>-1){job.location = "Gotha, DE";}
      if(job.location.indexOf("Hameln")>-1){job.location = "Hameln, DE";}
      if(job.location.indexOf("Neuwied")>-1){job.location = "Neuwied, DE";}  
      if(job.location.indexOf("Tübingen")>-1){job.location = "Tübingen, DE";}
      if(job.location.indexOf("Böblingen")>-1){job.location = "Böblingen, DE";}
      if(job.location.indexOf("Mühldorf am Inn")>-1){job.location = "Mühldorf am Inn, DE";}  
      if(job.location.indexOf("Recklinghausen")>-1){job.location = "Recklinghausen, DE";}
      if(job.location.indexOf("Itzehoe")>-1){job.location = "Itzehoe, DE";}
      if(job.location.indexOf("Frechen")>-1){job.location = "Frechen, DE";} 
      if(job.location.indexOf("Mölln")>-1){job.location = "Mölln, DE";}
      if(job.location.indexOf("Nürnberg")>-1){job.location = "Nürnberg, DE";}



         // Locaiones de Irlanda

        if(job.location.indexOf("Dublin")>-1){job.location = "Dublin, Ireland";}
        if(job.location.indexOf("Galway")>-1){job.location = "Galway, Ireland";}
        if(job.location.indexOf("Cork")>-1){job.location = "Cork, Ireland";}
        if(job.location.indexOf("Limerick")>-1){job.location = "Limerick, Ireland";}
        if(job.location.indexOf("Waterford")>-1){job.location = "Waterford, Ireland";}
        if(job.location.indexOf("Belfast")>-1){job.location = "Belfast, Northern Ireland";}
        if(job.location.indexOf("Kilkenny")>-1){job.location = "Kilkenny, Ireland";}
        if(job.location.indexOf("Londonderry")>-1){job.location = "Londonderry, Northern Ireland";}
        if(job.location.indexOf("Killarney")>-1){job.location = "Killarney, Ireland";}
        if(job.location.indexOf("Drogheda")>-1){job.location = "Drogheda, Ireland";}
        if(job.location.indexOf("Shannon")>-1){job.location = "Shannon, Ireland";}
        if(job.location.indexOf("Ennis")>-1){job.location = "Ennis, Ireland";}
        if(job.location.indexOf("Westport")>-1){job.location = "Westport, Ireland";}
        if(job.location.indexOf("Kinsale")>-1){job.location = "Kinsale, Ireland";}
        if(job.location.indexOf("Bray")>-1){job.location = "Bray, Ireland";}
        if(job.location.indexOf("Sligo")>-1){job.location = "Sligo, Ireland";}
        if(job.location.indexOf("Dundalk")>-1){job.location = "Dundalk, Ireland";}
        if(job.location.indexOf("Louth")>-1){job.location = "Louth, Ireland";}
        if(job.location.indexOf("Letterkenny")>-1){job.location = "Letterkenny, Ireland";}
        if(job.location.indexOf("Wexford")>-1){job.location = "Wexford, Ireland";}
        if(job.location.indexOf("Navan")>-1){job.location = "Navan, Ireland";}
        if(job.location.indexOf("Cobh")>-1){job.location = "Cobh, Ireland";}
        if(job.location.indexOf("Swords")>-1){job.location = "Swords, Ireland";}
        if(job.location.indexOf("Lisburn")>-1){job.location = "Lisburn, Ireland";}
        if(job.location.indexOf("Armagh")>-1){job.location = "Armagh, Northern Ireland";}
        if(job.location.indexOf("Blarney")>-1){job.location = "Blarney, Ireland";}
        if(job.location.indexOf("Newry")>-1){job.location = "Newry, Northern Ireland";}
        if(job.location.indexOf("Athlone")>-1){job.location = "Athlone, Ireland";}
        if(job.location.indexOf("Tralee")>-1){job.location = "Tralee, Ireland";}
        if(job.location.indexOf("Clonmel")>-1){job.location = "Clonmel, Ireland";}
        if(job.location.indexOf("Naas")>-1){job.location = "Naas, Ireland";}
        if(job.location.indexOf("Cashel")>-1){job.location = "Cashel, Ireland";}
        if(job.location.indexOf("Clifden")>-1){job.location = "Clifden, Ireland";}
        if(job.location.indexOf("Dún Laoghaire")>-1){job.location = "Dún Laoghaire, Ireland";}
        if(job.location.indexOf("Wicklow")>-1){job.location = "Wicklow, Ireland";}
        if(job.location.indexOf("Antrim")>-1){job.location = "Antrim, Northern Ireland";}
        if(job.location.indexOf("Carlow")>-1){job.location = "Carlow, Ireland";}
        if(job.location.indexOf("Greystones")>-1){job.location = "Greystones, Ireland";}
        if(job.location.indexOf("Mullingar")>-1){job.location = "Mullingar, Ireland";}
        if(job.location.indexOf("Adare")>-1){job.location = "Adare, Ireland";}
        if(job.location.indexOf("Portlaoise")>-1){job.location = "Portlaoise, Ireland";}
        if(job.location.indexOf("Tuam")>-1){job.location = "Tuam, Ireland";}
        if(job.location.indexOf("Trim")>-1){job.location = "Trim, Ireland";}
        if(job.location.indexOf("Castlebar")>-1){job.location = "Castlebar, Ireland";}
        if(job.location.indexOf("Ballina")>-1){job.location = "Ballina, Ireland";}
        if(job.location.indexOf("Arklow")>-1){job.location = "Arklow, Ireland";}
        if(job.location.indexOf("Mallow")>-1){job.location = "Mallow, Ireland";}
        if(job.location.indexOf("Tallaght")>-1){job.location = "Tallaght, Ireland";}
        if(job.location.indexOf("Leixlip")>-1){job.location = "Leixlip, Ireland";}
        if(job.location.indexOf("Thurles")>-1){job.location = "Thurles, Ireland";}